### ISSUE TITLE
[PyTorch - Geforce RTX 4070 Compatibility Issue] Training has been failed

### ISSUE THREAD

**Issue by sooyoungmoon** [FIGLAB/IMUPoser#10]
Hello, I'm Sooyoung and try to test your interesting model for pose estimation.

Motivation: I am planning to develop an application for coaching runner's pose for better performance based on research works including yours.

I followed the instruction in this repository. 
1. Downloading training data > Done
2. Preprocessing AMASS and DIP-IMU > Done
3. Training the model > Failed 

I have created an account for W&B (Weights & Biases). But unfortunately, there is no log for the step#3 above. By the way, I faced the following error right after I have executed the script for training.

"**_home/moon/miniconda3/envs/imuposer/lib/python3.7/site-packages/torch/cuda/__init__.py:146: UserWarning: 
NVIDIA GeForce RTX 4070 with CUDA capability sm_89 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37.
If you want to use the NVIDIA GeForce RTX 4070 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/_**"

From the error message, I guess the training has been failed due to a compatibility issue between my Graphic card (with CUDA capability sm_89) and the pytorch install (v1.12.1)
I tried to upgrade pytorch to recent versions (such as v11.8 or 12.1). It was not successful either.

Could you give me some tips to solve the issue? 

Thank you for your consideration.

**Comment by sooyoungmoon** [comment]
I think I have solved the issue!
I upgraded the python package to v3.8 and installed the pytorch-cuda v11.8 in my conda environment. After doing some minor changes, the training is being executed.
You don't have to worry about this issue. Thanks!
